SectionPagesMenu = ["main", "social"]
author = "Michael Humphrey"
baseurl = "/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "foundation-theme"
title = "Friends of Jack Dorr"
[[menu.social]]
name = "Instagram"
url = "http://instagram.com"
weight = 1
[[menu.social]]
name = "Facebook"
url = "https://www.facebook.com/groups/262701727595775/"
weight = 2
[params.footer]
ein = "84-2166095"
email = "trishadorr@gmail.com"
phone = "541-778-4960"
[params.hero]
btnblue = "Learn More"
btngreen = "Donate Now"
herodiscription = "![](/uploads/Jack-Dorr-2.jpg) Here we can share updates for fundraisers and events such as Jack's Dodgeball Olympics and similar to The Jack Frost Festival!"
herotitle = "Welcome to Friends of Jack Dorr"
[params.main]
contentOneBody = "Find updates on the [Friends of Jack page!](https://www.facebook.com/groups/262701727595775/)"
contentOneTitle = "Stay Connected!"
contentTwoBody = "You can donate [here:](https://www.paypal.com/pools/c/8jSnkG8SBb) through a PayPal Pool created for Friends of Jack Dorr."
contentTwoTitle = "Make a Donation. "
[params.meta]
description = "Here we can share updates for fundraisers and events."
keywords = "jack dorr, ashland oregon, "
