title = "Friends of Jack Dorr"
baseURL = "https://friendsofjackdorr.org"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = "3"
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  favicon = ""
  description = "Welcome to Friends of Jack Dorr."
  facebook = "https://www.facebook.com/groups/262701727595775/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  background_color_class = "bg-black"
  featured_image = "/uploads/BoysFirstDayofSchool_3055x761.jpg"
  recent_posts_number = 2
