DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
SectionPagesMenu = "main"
baseURL = "https://friendsofjackdorr.org"
enableRobotsTXT = true
googleAnalytics = "UA-154857416-1"
languageCode = "en-us"
theme = "ananke"
title = "Friends of Jack Dorr"
[params]
background_color_class = "bg-black"
description = "Welcome to Friends of Jack Dorr."
facebook = "https://www.facebook.com/groups/262701727595775/"
favicon = "/uploads/favicon-32x32.png"
featured_image = "/uploads/BoysFirstDayofSchool_3055x761.jpg"
github = ""
gitlab = ""
instagram = ""
linkedin = ""
mastodon = ""
recent_posts_number = "3"
slack = ""
twitter = ""
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
