title = "Friends of Jack Dorr"
baseURL = "https://friendsofjackdorr.org/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Welcome to Friends of Jack Dorr.  Get updates about the fundraisers and events such as Jack's Dodgeball Olympics and similar to The Jack Frost Festival! "
  facebook = "https://www.facebook.com/groups/262701727595775/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/uploads/Boys First Day of School.jpg"
  recent_posts_number = 2
